# fly.toml app configuration file generated for edit-price on 2025-07-24T11:33:44-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'edit-price'
primary_region = 'iad'

[env]
  MISE_PYTHON_COMPILE = "1"
  MISE_VERBOSE = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
